# alacritty.toml

[shell]
program = "/usr/bin/fish"
args = ["--login"]

[font]
size = 12

[window]
opacity = 0.75
blur = true
startup_mode = "Maximized"
title = "idk what im doing"

[selection]
save_to_clipboard = true

[colors.primary]
background = '#222436'
foreground = '#defffc'

[mouse]
hide_when_typing = true

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#a883eb'
cyan    = '#0bbcdb' 
white   = '#9699a8'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#0cd2f5' #7da6ff
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
